<a href="https://colab.research.google.com/github/SwatiKharat93/Data-Science-Practical/blob/main/practical_No_2_SDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name : Swati Kashinath Kharat
Roll No : A-69
Class : SY-A

1.What is Data Ingestion and why is it important? Which library is used?

Data ingestion is the process of collecting and importing data from different sources such as CSV files, databases, or APIs into a system for analysis. It is important in data science because without properly loading data, no analysis or machine learning can be performed. It ensures that data is available, organized, and ready for further processing. The most commonly used Python library for data ingestion and cleaning is Pandas, as it provides easy functions to load, manipulate, and clean datasets efficiently.

2.Why is data cleaning necessary before performing analysis or machine learning?

Data cleaning is necessary because raw data often contains errors such as missing values, duplicate records, incorrect formats, or irrelevant information. If this unclean data is used directly, it can lead to inaccurate analysis and poor performance of machine learning models. Cleaning the data improves its quality, ensures consistency, and helps in obtaining reliable and meaningful results.

3.How do you load a CSV file into a Pandas DataFrame?

A CSV file can be loaded into a Pandas DataFrame using the read_csv() function. First, the Pandas library is imported, and then the file is read by specifying its name or path. For example, import pandas as pd and then df = pd.read_csv('file_name.csv'). This command loads the data into a DataFrame called df, which can then be used for further analysis.

4.What is the difference between head() and tail() functions in Pandas?

The head() function is used to display the first few rows of a dataset, usually the first 5 rows by default, while the tail() function displays the last few rows of the dataset. These functions are useful for quickly understanding the structure and contents of the data without printing the entire dataset.

5.How can you identify missing values in a dataset?

Missing values in a dataset can be identified using functions like isnull() or isna() in Pandas. These functions return a Boolean result indicating whether a value is missing or not. By using df.isnull().sum(), we can count the number of missing values in each column. This helps in understanding which parts of the data need cleaning or preprocessing before analysis.*italicized text*

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
df = pd.read_csv('cloud_outages_dataset.csv')

In [ ]:
df.head()

,incident_id,cloud_provider,region,service,service_subtype,start_time,end_time,duration_minutes,severity,status,...,post_mortem_link,is_recurrent_issue,previous_incident_id,external_factors,scheduled_maintenance_conflict,patch_applied,system_load_before_outage,system_load_after_outage,backup_system_triggered,notes
0,aeb380d2-6559-4d99-abfb-17e1c45e831b,AWS,europe-west2,Storage,S3,2025-06-30 10:18:08.524480,2025-06-30 13:15:08.524480,177,Low,Monitoring,...,NaN,No,NaN,NaN,No,No,40,46,Yes,Simulated note
1,ddf7e3a0-f44d-4c94-ae32-189213321e2d,IBM,asia-southeast1,AI/ML,RDS,2025-06-28 10:18:08.524591,2025-06-28 20:52:08.524591,634,Low,Investigating,...,NaN,No,NaN,Weather,Yes,No,45,55,Yes,Simulated note
2,b17b9c80-94a0-4ca5-b52f-f1e7853b1240,AWS,europe-west2,Storage,S3,2025-06-01 10:18:08.524638,2025-06-01 14:36:08.524638,258,High,Resolved,...,NaN,No,NaN,DDoS,No,Yes,61,74,No,Simulated note
3,c856b404-e22e-4f84-8bed-9b1512adc9b5,AWS,asia-southeast1,Compute,Lambda,2025-11-30 10:18:08.524678,2025-11-30 19:21:08.524678,543,Medium,Resolved,...,NaN,Yes,NaN,Weather,No,Yes,48,97,Yes,Simulated note
4,42a85996-663a-4f92-94e1-0f205a06db01,IBM,asia-southeast1,AI/ML,Cloud Functions,2025-02-16 10:18:08.524719,2025-02-16 21:03:08.524719,645,Medium,Monitoring,...,NaN,No,NaN,DDoS,No,No,23,75,Yes,Simulated note

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 40 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   incident_id                     50000 non-null  object
 1   cloud_provider                  50000 non-null  object
 2   region                          50000 non-null  object
 3   service                         50000 non-null  object
 4   service_subtype                 50000 non-null  object
 5   start_time                      50000 non-null  object
 6   end_time                        50000 non-null  object
 7   duration_minutes                50000 non-null  int64
 8   severity                        50000 non-null  object
 9   status                          50000 non-null  object
 10  root_cause_category             50000 non-null  object
 11  root_cause_description          50000 non-null  object
 12  number_of_customers_affected    50000 non-null  int64
 13  estimated_revenue_loss_usd      50000 non-null  float64
 14  sla_violation                   50000 non-null  object
 15  region_impact_score             50000 non-null  int64
 16  service_impact_score            50000 non-null  int64
 17  ticket_count                    50000 non-null  int64
 18  ticket_response_time_minutes    50000 non-null  int64
 19  ticket_resolution_time_minutes  50000 non-null  int64
 20  monitoring_alerts_triggered     50000 non-null  int64
 21  detection_method                50000 non-null  object
 22  mitigation_action               50000 non-null  object
 23  number_of_engineers_involved    50000 non-null  int64
 24  engineer_response_time_minutes  50000 non-null  int64
 25  communication_channels_used     50000 non-null  object
 26  public_status_page_updated      50000 non-null  object
 27  status_page_update_count        50000 non-null  int64
 28  user_feedback_score             50000 non-null  int64
 29  post_mortem_completed           50000 non-null  object
 30  post_mortem_link                0 non-null      float64
 31  is_recurrent_issue              50000 non-null  object
 32  previous_incident_id            0 non-null      float64
 33  external_factors                37418 non-null  object
 34  scheduled_maintenance_conflict  50000 non-null  object
 35  patch_applied                   50000 non-null  object
 36  system_load_before_outage       50000 non-null  int64
 37  system_load_after_outage        50000 non-null  int64
 38  backup_system_triggered         50000 non-null  object
 39  notes                           50000 non-null  object
dtypes: float64(3), int64(14), object(23)
memory usage: 15.3+ MB

In [ ]:
df.isnull().sum()

incident_id                           0
cloud_provider                        0
region                                0
service                               0
service_subtype                       0
start_time                            0
end_time                              0
duration_minutes                      0
severity                              0
status                                0
root_cause_category                   0
root_cause_description                0
number_of_customers_affected          0
estimated_revenue_loss_usd            0
sla_violation                         0
region_impact_score                   0
service_impact_score                  0
ticket_count                          0
ticket_response_time_minutes          0
ticket_resolution_time_minutes        0
monitoring_alerts_triggered           0
detection_method                      0
mitigation_action                     0
number_of_engineers_involved          0
engineer_response_time_minutes        0
communication_channels_used           0
public_status_page_updated            0
status_page_update_count              0
user_feedback_score                   0
post_mortem_completed                 0
post_mortem_link                  50000
is_recurrent_issue                    0
previous_incident_id              50000
external_factors                  12582
scheduled_maintenance_conflict        0
patch_applied                         0
system_load_before_outage             0
system_load_after_outage              0
backup_system_triggered               0
notes                                 0
dtype: int64

In [ ]:
df.describe()

,duration_minutes,number_of_customers_affected,estimated_revenue_loss_usd,region_impact_score,service_impact_score,ticket_count,ticket_response_time_minutes,ticket_resolution_time_minutes,monitoring_alerts_triggered,number_of_engineers_involved,engineer_response_time_minutes,status_page_update_count,user_feedback_score,post_mortem_link,previous_incident_id,system_load_before_outage,system_load_after_outage
count,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,0.0,0.0,50000.000000,50000.000000
mean,361.312020,50297.95150,501118.383462,49.903620,49.974180,50.439280,32.554720,254.586100,10.552140,5.498960,32.503160,2.502740,2.997120,NaN,NaN,55.129780,54.900920
std,206.389101,28848.84549,288268.246858,29.169404,29.113495,28.907151,16.166142,130.332934,5.756397,2.873187,16.072899,1.715882,1.415214,NaN,NaN,26.356675,26.224833
min,5.000000,102.00000,1002.750000,0.000000,0.000000,1.000000,5.000000,30.000000,1.000000,1.000000,5.000000,0.000000,1.000000,NaN,NaN,10.000000,10.000000
25%,183.000000,25337.50000,249908.777500,25.000000,25.000000,25.000000,19.000000,141.000000,6.000000,3.000000,19.000000,1.000000,2.000000,NaN,NaN,32.000000,32.000000
50%,361.000000,50299.00000,502197.470000,50.000000,50.000000,50.000000,33.000000,255.000000,11.000000,6.000000,33.000000,3.000000,3.000000,NaN,NaN,55.000000,55.000000
75%,539.000000,75348.00000,751601.960000,75.000000,75.000000,76.000000,47.000000,367.000000,16.000000,8.000000,46.000000,4.000000,4.000000,NaN,NaN,78.000000,78.000000
max,720.000000,99999.00000,999992.080000,100.000000,100.000000,100.000000,60.000000,480.000000,20.000000,10.000000,60.000000,5.000000,5.000000,NaN,NaN,100.000000,100.000000

In [ ]:
df.isnull().sum()

incident_id                           0
cloud_provider                        0
region                                0
service                               0
service_subtype                       0
start_time                            0
end_time                              0
duration_minutes                      0
severity                              0
status                                0
root_cause_category                   0
root_cause_description                0
number_of_customers_affected          0
estimated_revenue_loss_usd            0
sla_violation                         0
region_impact_score                   0
service_impact_score                  0
ticket_count                          0
ticket_response_time_minutes          0
ticket_resolution_time_minutes        0
monitoring_alerts_triggered           0
detection_method                      0
mitigation_action                     0
number_of_engineers_involved          0
engineer_response_time_minutes        0
communication_channels_used           0
public_status_page_updated            0
status_page_update_count              0
user_feedback_score                   0
post_mortem_completed                 0
post_mortem_link                  50000
is_recurrent_issue                    0
previous_incident_id              50000
external_factors                  12582
scheduled_maintenance_conflict        0
patch_applied                         0
system_load_before_outage             0
system_load_after_outage              0
backup_system_triggered               0
notes                                 0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

Empty DataFrame
Columns: [incident_id, cloud_provider, region, service, service_subtype, start_time, end_time, duration_minutes, severity, status, root_cause_category, root_cause_description, number_of_customers_affected, estimated_revenue_loss_usd, sla_violation, region_impact_score, service_impact_score, ticket_count, ticket_response_time_minutes, ticket_resolution_time_minutes, monitoring_alerts_triggered, detection_method, mitigation_action, number_of_engineers_involved, engineer_response_time_minutes, communication_channels_used, public_status_page_updated, status_page_update_count, user_feedback_score, post_mortem_completed, post_mortem_link, is_recurrent_issue, previous_incident_id, external_factors, scheduled_maintenance_conflict, patch_applied, system_load_before_outage, system_load_after_outage, backup_system_triggered, notes]
Index: []

[0 rows x 40 columns]

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 40 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   incident_id                     0 non-null      object
 1   cloud_provider                  0 non-null      object
 2   region                          0 non-null      object
 3   service                         0 non-null      object
 4   service_subtype                 0 non-null      object
 5   start_time                      0 non-null      object
 6   end_time                        0 non-null      object
 7   duration_minutes                0 non-null      int64
 8   severity                        0 non-null      object
 9   status                          0 non-null      object
 10  root_cause_category             0 non-null      object
 11  root_cause_description          0 non-null      object
 12  number_of_customers_affected    0 non-null      int64
 13  estimated_revenue_loss_usd      0 non-null      float64
 14  sla_violation                   0 non-null      object
 15  region_impact_score             0 non-null      int64
 16  service_impact_score            0 non-null      int64
 17  ticket_count                    0 non-null      int64
 18  ticket_response_time_minutes    0 non-null      int64
 19  ticket_resolution_time_minutes  0 non-null      int64
 20  monitoring_alerts_triggered     0 non-null      int64
 21  detection_method                0 non-null      object
 22  mitigation_action               0 non-null      object
 23  number_of_engineers_involved    0 non-null      int64
 24  engineer_response_time_minutes  0 non-null      int64
 25  communication_channels_used     0 non-null      object
 26  public_status_page_updated      0 non-null      object
 27  status_page_update_count        0 non-null      int64
 28  user_feedback_score             0 non-null      int64
 29  post_mortem_completed           0 non-null      object
 30  post_mortem_link                0 non-null      float64
 31  is_recurrent_issue              0 non-null      object
 32  previous_incident_id            0 non-null      float64
 33  external_factors                0 non-null      object
 34  scheduled_maintenance_conflict  0 non-null      object
 35  patch_applied                   0 non-null      object
 36  system_load_before_outage       0 non-null      int64
 37  system_load_after_outage        0 non-null      int64
 38  backup_system_triggered         0 non-null      object
 39  notes                           0 non-null      object
dtypes: float64(3), int64(14), object(23)
memory usage: 0.0+ bytes

Empty DataFrame
Columns: [incident_id, cloud_provider, region, service, service_subtype, start_time, end_time, duration_minutes, severity, status, root_cause_category, root_cause_description, number_of_customers_affected, estimated_revenue_loss_usd, sla_violation, region_impact_score, service_impact_score, ticket_count, ticket_response_time_minutes, ticket_resolution_time_minutes, monitoring_alerts_triggered, detection_method, mitigation_action, number_of_engineers_involved, engineer_response_time_minutes, communication_channels_used, public_status_page_updated, status_page_update_count, user_feedback_score, post_mortem_completed, post_mortem_link, is_recurrent_issue, previous_incident_id, external_factors, scheduled_maintenance_conflict, patch_applied, system_load_before_outage, system_load_after_outage, backup_system_triggered, notes]
Index: []

[0 rows x 40 columns]

In [ ]:
import pandas as pd

# Reload the dataset to ensure it's not empty
df = pd.read_csv('cloud_outages_dataset.csv')

# Re-check for duplicates after reloading
initial_duplicate_count = df.duplicated().sum()
print(f"Initial number of duplicate rows: {initial_duplicate_count}")

df.drop_duplicates(inplace=True)

# Check again after dropping
duplicate_count_after_drop = df.duplicated().sum()
print(f"Number of duplicate rows after removal: {duplicate_count_after_drop}")
print(f"DataFrame shape after duplicate removal: {df.shape}")

Initial number of duplicate rows: 0
Number of duplicate rows after removal: 0
DataFrame shape after duplicate removal: (50000, 40)

In [ ]:
# Drop columns with all missing values
df.drop(columns=['post_mortem_link', 'previous_incident_id'], inplace=True)

# Fill missing values in 'external_factors' with 'Unknown'
df['external_factors'].fillna('Unknown', inplace=True)

print("Missing values after handling:")
display(df.isnull().sum()[df.isnull().sum() > 0])

/tmp/ipykernel_3867/3758715116.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['external_factors'].fillna('Unknown', inplace=True)

Missing values after handling:

Series([], dtype: int64)

In [ ]:
df['start_time'] = pd.to_datetime(df['start_time'])
df['end_time'] = pd.to_datetime(df['end_time'])

print("Data types after conversion:")
display(df[['start_time', 'end_time']].info())

Data types after conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   start_time  50000 non-null  datetime64[ns]
 1   end_time    50000 non-null  datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 781.4 KB

None

In [ ]:
# Example: Filter for incidents with 'High' severity
high_severity_incidents = df[df['severity'] == 'High']
print("Number of high severity incidents:", len(high_severity_incidents))

# Display the first 5 rows of the filtered data
display(high_severity_incidents.head())

Number of high severity incidents: 12346

,incident_id,cloud_provider,region,service,service_subtype,start_time,end_time,duration_minutes,severity,status,...,user_feedback_score,post_mortem_completed,is_recurrent_issue,external_factors,scheduled_maintenance_conflict,patch_applied,system_load_before_outage,system_load_after_outage,backup_system_triggered,notes
2,b17b9c80-94a0-4ca5-b52f-f1e7853b1240,AWS,europe-west2,Storage,S3,2025-06-01 10:18:08.524638,2025-06-01 14:36:08.524638,258,High,Resolved,...,1,Yes,No,DDoS,No,Yes,61,74,No,Simulated note
5,cc27ddaf-1511-4714-864f-133d6e946189,Oracle,asia-southeast1,Storage,Lambda,2025-04-14 10:18:08.524774,2025-04-14 19:20:08.524774,542,High,Resolved,...,1,Yes,Yes,Weather,Yes,No,93,82,Yes,Simulated note
7,eeab6d5c-123a-4d04-890c-542a7c4f31d1,IBM,us-west-2,AI/ML,Cloud Functions,2025-07-08 10:18:08.524843,2025-07-08 14:53:08.524843,275,High,Investigating,...,5,Yes,Yes,DDoS,Yes,Yes,93,29,No,Simulated note
11,abbc3c34-279e-4505-acd4-4c50dc3addd0,Azure,us-west-2,Database,S3,2025-06-09 10:18:08.524990,2025-06-09 20:38:08.524990,620,High,Resolved,...,5,No,Yes,DDoS,No,Yes,30,15,Yes,Simulated note
17,366204f5-78dd-4bbf-b482-7d26e5e8eddc,IBM,europe-west2,AI/ML,BigQuery,2025-03-20 10:18:08.525225,2025-03-20 18:21:08.525225,483,High,Monitoring,...,1,No,Yes,Vendor,Yes,Yes,11,72,Yes,Simulated note

In [ ]:
output_file_path = 'cloud_outages_cleaned.csv'
df.to_csv(output_file_path, index=False)
print(f"Cleaned data saved to {output_file_path}")

Cleaned data saved to cloud_outages_cleaned.csv